#!/bin/bash

# Copy Spack Config
SPACK=$SNAP_USER_COMMON

# Copy over Spack configs
if [ ! -f $SPACK/config.yaml ]; then
    cp $SNAP/spack/etc/spack/defaults/config.yaml $SPACK/config.yaml
    # Update default configs
    sed -i 's@root: \$spack/opt/spack@root: '"${SPACK}"'@g' $SPACK/config.yaml
    sed -i 's@\$spack@'"${SPACK}"'@g' $SPACK/config.yaml
fi 

if [ ! -f $SPACK/modules.yaml ]; then
    cp $SNAP/spack/etc/spack/defaults/modules.yaml $SPACK/modules.yaml
    # Modules point to Spack root
    sed -i 's@\$spack@'"${SPACK}"'@g' $SPACK/modules.yaml
fi

if [ ! -f $SPACK/compilers.yaml ]; then
    cat <<EOF >> $SPACK/compilers.yaml
    compilers:
    - compiler:
        spec: gcc@11.3.0
        paths:
          cc: $SNAP/usr/bin/gcc-11
          cxx: $SNAP/usr/bin/g++-11
          f77: null
          fc: null
        flags: {}
        operating_system: ubuntu_core22
        target: x86_64
        modules: []
        environment:
          prepend_path:
            LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAP_ARCH_TRIPLET
        extra_rpaths: []
EOF
fi

"$SNAP/spack/bin/spack" "$@"
