# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
---
name: spack
title: Spack
icon: data/spack-logo.svg
version: 0.19.2
adopt-info: spack
summary: A flexible package manager that supports multiple configurations.
description: |
  Spack is a multi-platform package manager that builds and installs multiple
   versions and configurations of software. It works on Linux, macOS, and many
   supercomputers. Spack is non-destructive: installing a new version of a
   package does not break existing installations, so many configurations of the
   same package can coexist.

  Spack offers a simple "spec" syntax that allows users to specify versions and
   configuration options. Package files are written in pure Python, and specs
   allow package authors to write a single script for many different builds of
   the same package. With Spack, you can build your software all the ways you
   want to.
license: Apache-2.0
website: https://spack.io/
base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

apps:
  spack:
    command: spack-wrapper
    environment:
      PATH: $SNAP/bin/usr/bin:$SNAP/bin/usr/lib:$PATH
      SPACK_SYSTEM_CONFIG_PATH: $SNAP_USER_COMMON
      MODULEPATH: $SNAP_USER_COMMON/share/spack/modules

parts:
  spack:
    plugin: dump
    source: >-
      https://github.com/spack/spack/releases/download/v$SNAPCRAFT_PROJECT_VERSION/spack-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    organize:
      ./*: spack/

  spack-wrapper:
    plugin: dump
    source: .
    stage:
      - spack-wrapper

  reqs:
    plugin: nil
    stage-packages:
      - build-essential
      - ca-certificates
      - coreutils
      - curl
      - environment-modules
      - gfortran
      - git
      - gpg
      - lsb-release
      - python3
      - python3-distutils
      - python3-venv
      - unzip
      - zip
    organize:
      ./*: bin/

  clingo:
    source: .
    plugin: python
    python-packages:
      - clingo

